#!/bin/bash
#run extended SP algorithm on problem set
SAVEIFS=$IFS
IFS=$(echo -en "\n\b")
FILES="cnf test files/*/*[^(?:Sym)].cnf"
ALGORITHM="build/release/bin/minisat_core"
ARGS="-activity-nl-freq=1"

for f in $FILES
do
	echo "Now Running $f"
	for i in {1..3}
	do
		echo "$f" "run" "$i" $>> "Output/outputnew.txt"
		$ALGORITHM "$ARGS" "$f" $>> "Output/outputnew.txt"
		echo "___________________________________________________________" $>> "Output/outputnew.txt"
	done
	echo "Done with $f"
done

for f in $FILES
do
	echo "Now Running $f"	
	for i in {1..3}
	do
		echo "$f" "run" "$i" $>> "Output/outputorig.txt"
		$ALGORITHM "$f" $>> "Output/outputorig.txt"
		echo "___________________________________________________________" $>> "Output/outputorig.txt"
	done
	echo "Done with $f"
done

IFS=$SAVEIFS
